# Generated by Django 4.2.4 on 2023-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='datetime',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
