# Generated by Django 4.2.4 on 2023-08-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_ticket_datetime_ticket_date_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='examinationConsultation',
            field=models.CharField(choices=[('كشف', 'كشف'), ('استشاره', 'استشاره')], default='كشف', max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservation_date',
            field=models.DateField(auto_created=True),
        ),
    ]
