# Generated by Django 4.2.4 on 2023-09-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_ticket_examinationconsultation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='notes',
        ),
    ]
