# Generated by Django 4.2.4 on 2023-08-28 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('doctor', 'doctor'), ('receptionist', 'receptionist'), ('super_user', 'super_user')], default='receptionist', max_length=12)),
                ('experience', models.FloatField(blank=True, default=0, null=True)),
                ('salary', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
