# Generated by Django 4.2.4 on 2023-08-28 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('city', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=1000)),
                ('continuous_calculation', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
