# Generated by Django 4.2.4 on 2023-08-28 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0003_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='1112664657-')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
