# Generated by Django 4.2.4 on 2023-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_operationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationimage',
            name='image',
            field=models.ImageField(upload_to='6504578259-'),
        ),
    ]
