# Generated by Django 4.2.4 on 2023-08-28 11:10

from django.db import migrations, models
import rules.file_uploader


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_operationimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationimage',
            name='image',
            field=models.ImageField(upload_to=rules.file_uploader.image_uploader),
        ),
    ]
