# Generated by Django 4.2.4 on 2023-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_operationimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='remaining_amount',
            field=models.IntegerField(default=0),
        ),
    ]
