# Generated by Django 4.2.4 on 2023-08-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_prescription_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='datetime',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
